# fly.toml app configuration file generated for serverpalaciogame-uvgfkw on 2025-06-08T21:42:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'serverpalaciogame-uvgfkw'
primary_region = 'iad'

[build]

[[services]]
  internal_port = 3500
  protocol = "udp"

  [[services.ports]]
    port = 3500

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

