# fly.toml app configuration file generated for serverpalaciogame on 2025-06-08T23:30:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "serverpalaciogame"
primary_region = "iad"

[build]

[[services]]
  internal_port = 3500
  protocol = "udp"

  [[services.ports]]
    port = 3500
    handlers = ["udp"]

[[services]]
  internal_port = 3500
  protocol = "tcp"

  [[services.ports]]
    port = 3500
    handlers = ["tcp"]

auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1


